obj-$(CONFIG_MACH_HOLIDAY) += board-holiday.o
obj-$(CONFIG_MACH_HOLIDAY) += board-holiday-gpiomux.o
obj-$(CONFIG_MACH_HOLIDAY) += board-holiday-keypad.o
obj-$(CONFIG_MACH_HOLIDAY) += board-holiday-mmc.o
obj-$(CONFIG_MACH_HOLIDAY) += board-holiday-storage.o
obj-$(CONFIG_MACH_HOLIDAY) += board-holiday-wifi.o
obj-$(CONFIG_MACH_HOLIDAY) += board-holiday-regulator.o
obj-$(CONFIG_MACH_HOLIDAY) += board-holiday-pmic.o
obj-$(CONFIG_MACH_HOLIDAY) += board-holiday-audio.o
obj-$(CONFIG_MACH_HOLIDAY) += board-holiday-rfkill.o
ifeq ($(CONFIG_MSM_CAMERA),y)
obj-$(CONFIG_MACH_HOLIDAY) += board-holiday-camera.o
endif
obj-$(CONFIG_MACH_HOLIDAY) += display/

